name: salvador_desktop
description: Interface desktop para o agente local Salvador CLI.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_markdown_plus: ^1.0.12
  get_it: ^9.2.1
  salvador_cli:
    path: ..
  url_launcher: ^6.3.2
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  checks: ^0.3.1

flutter:
  uses-material-design: true
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-VariableFont_wdth,wght.ttf
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
